# Generated by Django 2.1.7 on 2019-03-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=60)),
                ('linkedin', models.CharField(blank=True, max_length=60)),
                ('github', models.CharField(blank=True, max_length=60)),
                ('twitter', models.CharField(blank=True, max_length=60)),
                ('profile_pic', models.ImageField(blank=True, default='profie_pic/default-user.jpg', upload_to='profile_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
