# Generated by Django 2.1.7 on 2019-03-30 18:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190330_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default-user.jpg', upload_to=users.models.imagepath),
        ),
    ]
