# Generated by Django 2.1.7 on 2019-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190331_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='firstname',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='lastname',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='middlename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
