# Generated by Django 2.1.7 on 2019-04-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190402_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='middlename',
        ),
    ]
