# Generated by Django 2.1.7 on 2019-04-02 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_siteuser_middlename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='firstname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='siteuser',
            old_name='lastname',
            new_name='Last_name',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='Email_address',
            field=models.EmailField(default=datetime.datetime(2019, 4, 2, 16, 38, 33, 263648, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
