# Generated by Django 2.1.7 on 2019-04-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190402_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='Email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
