# Generated by Django 2.1.7 on 2019-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190404_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='bio',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
