# Generated by Django 2.1.7 on 2019-04-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190402_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Vote'),
            preserve_default=False,
        ),
    ]
