# Generated by Django 2.1.7 on 2019-04-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Vote'),
        ),
    ]
