# Generated by Django 2.1.7 on 2019-04-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
