# Generated by Django 2.1.7 on 2019-04-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
